# Generated by Django 2.2.13 on 2001-12-31 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=35)),
                ('name', models.CharField(max_length=35)),
                ('email', models.EmailField(max_length=35)),
                ('password', models.CharField(max_length=35)),
                ('date', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
