# Generated by Django 2.2.13 on 2021-01-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('image', models.ImageField(upload_to='uploaded_images')),
                ('price', models.IntegerField(max_length=5)),
                ('category', models.ForeignKey(default='category not avialable', on_delete=django.db.models.deletion.CASCADE, to='cafeitems.Menu')),
            ],
        ),
    ]
