# Generated by Django 2.2.13 on 2001-12-31 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeitems', '0002_auto_20210111_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(upload_to='uploaded_images/'),
        ),
    ]
